### ISSUE TITLE
Openssl 1.0.2e

### ISSUE THREAD

**Issue by rolnick** [evekb/evedev-kb#51] opened 2016-01-20 09:44 UTC
Hi,

Recently I updated openssl 1.0.2d to 1.0.2e and i can't fetch killmails from API.

When I run:  /usr/local/www/kb/cron/cron_api.php

> i got: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac (Code: 35)

or:

> <b>WARNING</b> [2] Invalid argument supplied for foreach()<br />
> Error on line 46 in file /usr/local/www/kb/common/includes/api/class.killlog.php<br />
> PHP 5.6.17 (FreeBSD), EDK 4.2.17.0 (Frostline 1.0)<br />
> File: /usr/local/www/kb/common/includes/api/class.killlog.php, line: 46, class: EDKError, function: handler<br />
> File: /usr/local/www/kb/cron/cron_api.php, line: 89, class: API_KillLog, function: Import<br />

for all keys.

I can fetch killmails from zkb without any errors.

After downgrade to 1.0.2d everthing works.

Rolnick

**Comment by Salvoxia** [comment] 2016-01-26 16:48
Hi,

I tried to reproduce this problem with OpenSSL 1.0.2e and did not succeed. I'm not using FreeBSD, though.
So I have to admit, I'm inclined to point fingers towards OpenSSl...

Best Regards,
Salvoxia

**Comment by rolnick** [comment] 2016-02-01 15:10
Hi,

But if i switch from curl to file i get:

> HTTP Request Failed

After update to OpenSSL/1.0.2f problem persists.
Rolnick

**Comment by Salvoxia** [comment] 2016-02-01 16:00
Hi,

what does the troubleshooting page in ACP show for XML API and CREST API connectivity for cURL and file, respectively?

Best Regards,
Salvoxia

**Comment by rolnick** [comment] 2016-02-01 17:11
Hi,

Curl:

> Connection to XML API NOT successul, Error: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac (Code: 35)
> 
> Connection to CREST API NOT successul, Error: Error getting data: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac(35) (Code: 0)

File:

> Connection to XML API NOT successul, Error: HTTP Request Failed (Code: 0)
> 
> Connection to CREST API NOT successul, Error: Error getting data: HTTP , URL: https://public-crest.eveonline.com/killmails/33493676/553ac7e2aeabe48092bde10958de0a44dc6f35ef/ (Code: 0)

Rolnick

**Comment by Salvoxia** [comment] 2016-02-01 19:37
Hi,

it's a long shot, but could you please try the following (to confirm or deny my hunch):
In common/includes/class.simplecrest.php find the following code block (around line 103):

``` php
curl_setopt(self::$curl, CURLOPT_URL, $url);
curl_setopt(self::$curl, CURLOPT_HTTPHEADER, $headers);
curl_setopt(self::$curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt(self::$curl, CURLOPT_USERAGENT, self::$USER_AGENT);
```

and append this line:

``` php
curl_setopt(self::$curl, CURLOPT_SSL_CIPHER_LIST, 'AES256');
```

And then check whether the connectivity state for CREST on the troubleshooting page changed.

Best Regards,
Salvoxia

**Comment by rolnick** [comment] 2016-02-01 20:04
It did not change anything. 
I disabled 

> ssl_ciphers 'kEECDH+ECDSA+AES128 kEECDH+ECDSA+AES256 kEECDH+AES128 kEECDH+AES256 +SHA !aNULL !eNULL !LOW !MD5 !EXP !DSS !PSK !SRP !kECDH !CAMELLIA !RC4 !SEED';

in **nginx.conf** for test, but it  was blind shoot. Weird, because in console **curl** works.

**Comment by Salvoxia** [comment] 2016-02-02 06:20
Well, frankly I'm running out of ideas. 
The XML API and CREST use different certificates, but since you CAN fetch from zKillboard it doesn't look like a certificate issue. So I thought a change in preferred Cipher suites in the new OpenSSL versions and some configuration-thing on CCP's server side might be responsible..

**Comment by rolnick** [comment] 2016-02-02 07:27
Hi,

I will wait until CCP upgrades SSL on the servers. Righ now it does not support TLS 1.1 or 1.2.

You can check it on [https://www.ssllabs.com/ssltest/analyze.html?d=public-crest.eveonline.com](https://www.ssllabs.com/ssltest/analyze.html?d=public-crest.eveonline.com)

Rolnick

**Comment by regner** [comment] 2016-02-02 08:40
@rolnick I hope to get that SSL issue for CREST sorted out in the next 2 months. It requires a surprisingly large rewrite of a few things which I have finished the first pass on but now need to get through testing and into a release.

**Comment by rolnick** [comment] 2016-02-14 09:53
Hi, 

I had some time, so i tested somethnig. I changed:
`curl_setopt(self::$curl, CURLOPT_SSL_CIPHER_LIST, 'AES256');`
to
`curl_setopt(self::$curl, CURLOPT_SSL_CIPHER_LIST, 'RC4-SHA');`
and i got:

> Successfully connected to CREST API

but

> Connection to XML API NOT successul, Error: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac (Code: 35)

Then I checked:
`sslscan public-crest.eveonline.com | grep Accepted`

> Accepted  TLSv1  256 bits  AES256-SHA
>     Accepted  TLSv1  128 bits  AES128-SHA
>     Accepted  TLSv1  128 bits  RC4-SHA
>     Accepted  TLSv1  128 bits  RC4-MD5
>     Accepted  TLSv1  112 bits  DES-CBC3-SHA 
> Prefered Server Cipher(s):
>     TLSv1  128 bits  RC4-SHA

And 
`sslscan api.eveonline.com | grep Accepted`

>   Accepted  TLSv1  256 bits  AES256-SHA
>     Accepted  TLSv1  128 bits  AES128-SHA
>     Accepted  TLSv1  112 bits  DES-CBC3-SHA
> Prefered Server Cipher(s):
>     TLSv1  256 bits  AES256-SHA

I was trying other ciphers with no luck.

Rolnick

**Comment by Salvoxia** [comment] 2016-02-15 15:10
Ok, then it would be interested what Cipher is negotiated if no explicit cipher list is set, and why that cipher or the server's response breaks OpenSSL...

**Comment by rolnick** [comment] 2016-02-16 22:09
Hi, 
I think i found what is a problem. When i am using OpenSSL 1.0.2e the php56-curl is compiling with warning:

>   warning: #warning "libcurl was compiled with SSL support, but configure could not determine which " "library was used; thus no SSL crypto locking callbacks will be set, which may " "cause random crashes on SSL requests"

FreeBSD has  own build in openssl, right now: OpenSSL 1.0.1p-freebsd. But all programs should use OpenSSL 1.0.2e. Somehow php56-curl is mixing libraries from them.

I will write to the maintainer of the port ftp/php56-curl to repair it.

Rolnick

**Comment by Salvoxia** [comment] 2016-02-19 06:38
Hi,

it's great you found the culprit! Let's hope the maintainer will supply a fix for this asap!
Would let me know how this issue turned out in the end?

Best Regards,
Salvoxia

**Comment by rolnick** [comment] 2016-02-23 16:10
Hi,
I found solution. I don’t know why, but extensions in **extensions.ini** should be in correct order. So in my case, I had:
`extension=smbclient.so`
`extension=ldap.so`
`....`
`extension=curl.so`

After some changes to:
`extension=ldap.so`
`extension=smbclient.so`
`....`
`extension=curl.so`

Everything works like charm.

Rolnick

**Closed as completed** 2016-02-24 15:21 UTC

**Comment by Salvoxia** [comment] 2016-02-25 09:31
Hi,

thanks for sharing the solution!
I need to remember that one.

Best Regards,
Salvoxia
